version: "3.9"

services:
  cinemax:
    build:
      context: ./cinemax-backend
      target: builder
    image: cinemax
    environment:
      secret: "pepinilloRick"
      TZ: "America/Mexico_City"
    ports:
      - 8080:8080
    volumes:
      - ./cinemax-backend:/go/src/app
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "cinemax"
      POSTGRES_PASSWORD: "cinemax"
      POSTGRES_DB: "cinemax"
      TZ: "America/Mexico_City"
    volumes:
      - ./cinemax-backend/db/models.sql:/docker-entrypoint-initdb.d/init.sql
      - ./cinemax-backend/db/carga_inicial.sql:/docker-entrypoint-initdb.d/load.sql
  client:
    build: ./cinemax-client
    ports:
      - 80:80
    stdin_open: true
    tty: true
    volumes:
      - "/app/node_modules" 
      - ".:/app"