CREATE TABLE "TIPO_SALA"(
    "TIPO_SALA_ID"  int4            GENERATED ALWAYS AS IDENTITY,
    "CLAVE"         varchar(2)      NOT NULL,
    "DESCRIPCION"   varchar(255)    NOT NULL,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "TIPO_SALA_PK" PRIMARY KEY ("TIPO_SALA_ID")
)
;

-- 
-- TABLE: "SALA" 
--
CREATE TABLE "SALA"(
    "SALA_ID"       int4            GENERATED ALWAYS AS IDENTITY,
    "NOMBRE"        varchar(40)     NOT NULL,
    "DESCRIPCION"   varchar(255)    NOT NULL,
    "UBICACION"     varchar(255)    NOT NULL,
    "TIPO_SALA_ID"  int4            NOT NULL,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "SALA_PK" PRIMARY KEY ("SALA_ID"), 
    CONSTRAINT "SALA_TIPO_SALA_ID_FK" FOREIGN KEY ("TIPO_SALA_ID")
    REFERENCES "TIPO_SALA"("TIPO_SALA_ID")
)
;

-- 
-- TABLE: "ASIENTO" 
--
CREATE TABLE "ASIENTO"(
    "ASIENTO_ID"  int4          GENERATED ALWAYS AS IDENTITY,
    "CLAVE"       varchar(3)    NOT NULL,
    "SALA_ID"     int4          NOT NULL,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "ASIENTO_PK" PRIMARY KEY ("ASIENTO_ID"), 
    CONSTRAINT "ASIENTO_SALA_ID_FK" FOREIGN KEY ("SALA_ID")
    REFERENCES "SALA"("SALA_ID")
)
;

-- 
-- TABLE: "CLASIFICACION" 
--
CREATE TABLE "CLASIFICACION"(
    "CLASIFICACION_ID"  int4           GENERATED ALWAYS AS IDENTITY,
    "CLAVE"             varchar(3)     NOT NULL,
    "DESCRIPCION"       varchar(100)   NOT NULL,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "CLASIFICACION_PK" PRIMARY KEY ("CLASIFICACION_ID")
)
;

-- 
-- TABLE: "IDIOMA" 
--
CREATE TABLE "IDIOMA"(
    "IDIOMA_ID"  int4           GENERATED ALWAYS AS IDENTITY,
    "NOMBRE"     varchar(40)    NOT NULL,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "IDIOMA_PK" PRIMARY KEY ("IDIOMA_ID")
)
;

-- 
-- TABLE: "GENERO" 
--
CREATE TABLE "GENERO"(
    "GENERO_ID"  int4           GENERATED ALWAYS AS IDENTITY,
    "NOMBRE"     varchar(40)    NOT NULL,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "GENERO_PK" PRIMARY KEY ("GENERO_ID")
)
;


-- 
-- TABLE: "PELICULA" 
--
CREATE TABLE "PELICULA"(
    "PELICULA_ID"           int4             GENERATED ALWAYS AS IDENTITY,
    "NOMBRE"                varchar(40)      NOT NULL,
    "DIRECTOR"              varchar(255)     NOT NULL,
    "DESCRIPCION"           varchar(255)     NOT NULL,
    "DURACION_MINUTOS"      int4             NOT NULL,
    "ANIO"                  varchar(4)       NOT NULL,
    "FECHA_DISPONIBILIDAD"  timestamp        NOT NULL,
    "IMAGEN"                varchar                  ,
    "RESENA"                varchar(1000)    NOT NULL,
    "CLASIFICACION_ID"      int4             NOT NULL,
    "IDIOMA_ID"             int4             NOT NULL,
    "SUBTITULO_ID"          int4,
    "GENERO_ID"             int4             NOT NULL,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "PELICULA_PK" PRIMARY KEY ("PELICULA_ID"), 
    CONSTRAINT "PELICULA_CLASIFICACION_ID_FK" FOREIGN KEY ("CLASIFICACION_ID")
    REFERENCES "CLASIFICACION"("CLASIFICACION_ID"),
    CONSTRAINT "PELICULA_IDIOMA_ID_FK" FOREIGN KEY ("IDIOMA_ID")
    REFERENCES "IDIOMA"("IDIOMA_ID"),
    CONSTRAINT "PELICULA_SUBTITULO_ID_FK" FOREIGN KEY ("SUBTITULO_ID")
    REFERENCES "IDIOMA"("IDIOMA_ID"),
    CONSTRAINT "PELICULA_GENERO_ID_FK" FOREIGN KEY ("GENERO_ID")
    REFERENCES "GENERO"("GENERO_ID")
)
;

-- 
-- TABLE: "FUNCION" 
--
CREATE TABLE "FUNCION"(
    "FUNCION_ID"   int4         GENERATED ALWAYS AS IDENTITY,
    "FECHA_INICIO" timestamp    NOT NULL,
    "FECHA_FIN"    timestamp    NOT NULL,
    "PELICULA_ID"  int4         NOT NULL,
    "SALA_ID"      int4         NOT NULL,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "FUNCION_PK" PRIMARY KEY ("FUNCION_ID"), 
    CONSTRAINT "FUNCION_PELICULA_ID_FK" FOREIGN KEY ("PELICULA_ID")
    REFERENCES "PELICULA"("PELICULA_ID"),
    CONSTRAINT "FUNCION_SALA_ID_FK" FOREIGN KEY ("SALA_ID")
    REFERENCES "SALA"("SALA_ID")
)
;

-- 
-- TABLE: "EMPLEADO" 
--
CREATE TABLE "EMPLEADO"(
    "EMPLEADO_ID"  int4            GENERATED ALWAYS AS IDENTITY,
    "NOMBRE"       varchar(40)     NOT NULL,
    "AP_PATERNO"   varchar(40)     NOT NULL,
    "AP_MATERNO"   varchar(40)     NOT NULL,
    "RFC"          varchar(40)     NOT NULL,
    "EDAD"         int4            NOT NULL,
    "EMAIL"        varchar(255)    NOT NULL,
    "DIRECCION"    varchar(255)    NOT NULL,
    "TELEFONO"     varchar(10)     NOT NULL,
    "PASSWORD"     varchar(60)     NOT NULL,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "EMPLEADO_PK" PRIMARY KEY ("EMPLEADO_ID"),
    CONSTRAINT "EMPLEADO_EMAIL_UK"    UNIQUE ("EMAIL"),
    CONSTRAINT "EMPLEADO_TELEFONO_UK" UNIQUE ("TELEFONO")
)
;

-- 
-- TABLE: "CLIENTE" 
--
CREATE TABLE "CLIENTE"(
    "CLIENTE_ID"  int4            GENERATED ALWAYS AS IDENTITY,
    "NOMBRE"      varchar(40)     NOT NULL,
    "AP_PATERNO"  varchar(40)     NOT NULL,
    "AP_MATERNO"  varchar(40),
    "EMAIL"       varchar(255)    NOT NULL,
    "TELEFONO"    varchar(10)     NOT NULL,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("CLIENTE_ID")
)
;

-- 
-- TABLE: "TICKET" 
--
CREATE TABLE "TICKET"(
    "TICKET_ID"     int4              GENERATED ALWAYS AS IDENTITY,
    "FECHA_COMPRA"  timestamp         NOT NULL,
    "MONTO"         numeric(10, 2)    NOT NULL,
    "FUNCION_ID"    int4              NOT NULL,
    "CLIENTE_ID"    int4,
    "EMPLEADO_ID"   int4              NOT NULL,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "TICKET_PK" PRIMARY KEY ("TICKET_ID"), 
    CONSTRAINT "TICKET_FUNCION_ID_FK" FOREIGN KEY ("FUNCION_ID")
    REFERENCES "FUNCION"("FUNCION_ID"),
    CONSTRAINT "TICKET_EMPLEADO_ID_FK" FOREIGN KEY ("EMPLEADO_ID")
    REFERENCES "EMPLEADO"("EMPLEADO_ID"),
    CONSTRAINT "TICKET_CLIENTE_ID_FK" FOREIGN KEY ("CLIENTE_ID")
    REFERENCES "CLIENTE"("CLIENTE_ID")
)
;

-- 
-- TABLE: "TIPO_BOLETO" 
--
CREATE TABLE "TIPO_BOLETO"(
    "TIPO_BOLETO_ID"  int4            GENERATED ALWAYS AS IDENTITY,
    "CLAVE"           varchar(15)     NOT NULL,
    "DESCRIPCION"     varchar(255)    NOT NULL,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "TIPO_BOLETO_FK" PRIMARY KEY ("TIPO_BOLETO_ID")
)
;

-- 
-- TABLE: "BOLETO" 
--
CREATE TABLE "BOLETO"(
    "BOLETO_ID"       int4    GENERATED ALWAYS AS IDENTITY,
    "TICKET_ID"       int4    NOT NULL,
    "TIPO_BOLETO_ID"  int4    NOT NULL,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "BOLETO_PK" PRIMARY KEY ("BOLETO_ID"), 
    CONSTRAINT "BOLETO_TICKET_ID" FOREIGN KEY ("TICKET_ID")
    REFERENCES "TICKET"("TICKET_ID"),
    CONSTRAINT "BOLETO_TIPO_BOLETO_ID_FK" FOREIGN KEY ("TIPO_BOLETO_ID")
    REFERENCES "TIPO_BOLETO"("TIPO_BOLETO_ID")
)
;

-- 
-- TABLE: "STATUS_ASIGNACION_ASIENTO" 
--
CREATE TABLE "STATUS_ASIGNACION_ASIENTO"(
    "STATUS_ASIENTO_ID"  int4           GENERATED ALWAYS AS IDENTITY,
    "CLAVE"              varchar(15)    NOT NULL,
    "DESCRIPCION"        varchar(100)   NOT NULL,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "STATUS_ASIGNACION_ASIENTO_PK" PRIMARY KEY ("STATUS_ASIENTO_ID")
)
;

-- 
-- TABLE: "TRANSACCION" 
--
CREATE TABLE "TRANSACCION"(
    "TRANSACCION_ID" int4           GENERATED ALWAYS AS IDENTITY,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "TRANSACCION_PK" PRIMARY KEY ("TRANSACCION_ID")
)
;


-- 
-- TABLE: "ASIGNACION_ASIENTO" 
--
CREATE TABLE "ASIGNACION_ASIENTO"(
    "ASIGNACION_ASIENTO_ID"  int4    GENERATED ALWAYS AS IDENTITY,
    "ASIENTO_ID"         int4    NOT NULL,
    "FUNCION_ID"  int4    NOT NULL,
    "BOLETO_ID"          int4,
    "STATUS_ASIENTO_ID"  int4    NOT NULL,
    "TRANSACCION_ID"     int4,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "ASIGNACION_ASIENTO_PK" PRIMARY KEY ("ASIGNACION_ASIENTO_ID"), 
    CONSTRAINT "ASIENTO_ID_FK" FOREIGN KEY ("ASIENTO_ID")
    REFERENCES "ASIENTO"("ASIENTO_ID"),
    CONSTRAINT "STATUS_ASIGNACION_FUNCION_FK" FOREIGN KEY ("FUNCION_ID")
    REFERENCES "FUNCION"("FUNCION_ID"),
    CONSTRAINT "BOLETO_ID_FK" FOREIGN KEY ("BOLETO_ID")
    REFERENCES "BOLETO"("BOLETO_ID"),
    CONSTRAINT "STATUS_ASIGNACION_ASIENTO_FK" FOREIGN KEY ("STATUS_ASIENTO_ID")
    REFERENCES "STATUS_ASIGNACION_ASIENTO"("STATUS_ASIENTO_ID"),
    CONSTRAINT "STATUS_ASIGNACION_TRANSACCION_FK" FOREIGN KEY ("TRANSACCION_ID")
    REFERENCES "TRANSACCION"("TRANSACCION_ID")
)
;

-- 
-- TABLE: "PRECIO_BOLETO" 
--
CREATE TABLE "PRECIO_BOLETO"(
    "PRECIO_BOLETO_ID"  int4             GENERATED ALWAYS AS IDENTITY,
    "PRECIO"            numeric(6, 2)    NOT NULL,
    "TIPO_BOLETO_ID"    int4             NOT NULL,
    "TIPO_SALA_ID"      int4             NOT NULL,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "PRECIO_BOLETO_PK" PRIMARY KEY ("PRECIO_BOLETO_ID"), 
    CONSTRAINT "TIPO_BOLETO_KF" FOREIGN KEY ("TIPO_BOLETO_ID")
    REFERENCES "TIPO_BOLETO"("TIPO_BOLETO_ID"),
    CONSTRAINT "TIPO_SALA_FK" FOREIGN KEY ("TIPO_SALA_ID")
    REFERENCES "TIPO_SALA"("TIPO_SALA_ID")
)
;

-- 
-- TABLE: "TARJETA_PUNTOS" 
--

CREATE TABLE "TARJETA_PUNTOS"(
    "TARJETA_ID"     int4           GENERATED ALWAYS AS IDENTITY,
    "CODIGO_BARRAS"  varchar(15)    NOT NULL,
    "PUNTOS"         int4           NOT NULL,
    "CLIENTE_ID"     int4           NOT NULL,
    "CREATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    "UPDATED_AT"   timestamp        NOT NULL DEFAULT NOW(),
    CONSTRAINT "TARJETA_PUNTOS_PK" PRIMARY KEY ("TARJETA_ID"), 
    CONSTRAINT "CLIENTE_FK" FOREIGN KEY ("CLIENTE_ID")
    REFERENCES "CLIENTE"("CLIENTE_ID")
)
;